### ISSUE TITLE
1.11.2 Updating from 2.44 to 2.45 causes crash on MC start

### ISSUE THREAD

**Issue by joernott** [Szewek/Minecraft-Flux#14]
Hello,

replacing 2.4.4 with 2.4.5 caused the following crash on starting MC

`
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FCFMLCorePlugin (FinderCompass-1.11.2.jar)
  RebornCoreASM (RebornCore-1.11.2-2.13.4.37-universal.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.1.jar)
  LoadingPlugin (RandomThings-MC1.11.2-3.7.9.jar)
  LoadingPlugin (Quark-r1.2-82.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.6.jar)
  CorePlugin (FluxedRedstone-2.6.0.54.jar)
  CXLibraryCore (cxlibrary-1.11.2-1.4.0.jar)
  RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  SFRCore (SolarFluxReborn_1.11.2-2.12r.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 3/3/17 12:05 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tesla Essentials (modsquad)
Caused by: java.lang.ExceptionInInitializerError
	at com.trials.modsquad.proxy.ClientProxy.init(ClientProxy.java:26)
	at com.trials.modsquad.ModSquad.init(ModSquad.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:828)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at szewek.mcflux.MCFluxEvents.wrapEntity(MCFluxEvents.java:103)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_283_MCFluxEvents_wrapEntity_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:582)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:558)
	at net.minecraft.entity.Entity.<init>(Entity.java:212)
	at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:50)
	at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:63)
	at com.trials.modsquad.block.tile.render.RendererToaster.<clinit>(RendererToaster.java:16)
	... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1910409904 bytes (1821 MB) / 2998521856 bytes (2859 MB) up to 4241293312 bytes (4044 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2252 142 mods loaded, 142 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2252.jar) 
	UCHI	forge{13.20.0.2252} [Minecraft Forge] (forge-1.11.2-13.20.0.2252.jar) 
	UCHI	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHI	backpacks16840{3.1.6} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.6.jar) 
	UCHI	uncraftingtable{1.7.1-pre5} [Uncrafting Table] ([1.11.2]UncraftingTable-1.7.1-pre5.jar) 
	UCHI	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHI	aroma1997sdimension{1.0} [Aroma1997sDimension] (Aroma1997s-Dimensional-World-1.11.2-1.3.0.0.b31.jar) 
	UCHI	quark{r1.2-82} [Quark] (Quark-r1.2-82.jar) 
	UCHI	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHI	battletowers{1.5.5} [Battle Towers] (BattleTowers-1.11.2.jar) 
	UCHI	baubles{1.4.2} [Baubles] (Baubles-1.11-1.4.2.jar) 
	UCHI	bdlib{1.13.1.5} [BD Lib] (bdlib-1.13.1.5-mc1.11.2.jar) 
	UCHI	betterachievements{0.4.1.44} [Better Achievements] (BetterAchievements-1.11.2-0.4.1.44.jar) 
	UCHI	betterbuilderswands{0.10.2} [Better Builder's Wands] (BetterBuildersWands-1.11-0.10.2.225+14b290d.jar) 
	UCHI	hammercore{1.2.8} [Hammer Core] (HammerCore_1.11.2-1.2.8.jar) 
	UCHI	blackholestorage{4b} [Black Hole Storage] (Black Hole Storage 1.11.2-4b.jar) 
	UCHE	cfm{4.1.1} [MrCrayfish's Furniture Mod] (cfm-4.1.1-mc1.11.2.jar) 
	UCHI	chiselsandbits{13.9} [Chisels & Bits] (chiselsandbits-13.9.jar) 
	UCHI	colors{1.0.0} [Colors] (Colors-1.11-1.0.0.jar) 
	UCHI	cyclopscore{0.9.3} [Cyclops Core] (CyclopsCore-1.11.2-0.9.3.jar) 
	UCHI	commoncapabilities{1.3.1} [CommonCapabilities] (CommonCapabilities-1.11.2-1.3.1.jar) 
	UCHI	jei{4.2.4.226} [Just Enough Items] (jei_1.11.2-4.2.4.226.jar) 
	UCHI	convenientadditions{1.1-28} [Convenient Additions] (ConvenientAdditions-1.1-build28.jar) 
	UCHI	csaddle{1.2} [Craftable Saddles] (Craftable Saddles- MC1.11.jar) 
	UCHI	forestry{5.3.1.44} [Forestry] (forestry_1.11.2-5.3.1.44.jar) 
	UCHI	eleccore{1.7.9999.custom} [ElecCore] (ElecCore-1.11-1.7.402.jar) 
	UCHI	craftingtableiv{1.0} [CraftingTable-IV] (CraftingTableIV-1.4.110.jar) 
	UCHI	cxlibrary{1.4.0} [CXLibrary] (cxlibrary-1.11.2-1.4.0.jar) 
	UCHI	deathquotes{1.0.1} [Death Quotes] (deathquotes-1.0.1-mc1.11.2-forgeBeta.jar) 
	UCHI	durabilityshow{4.1.0} [Durability Show] (Durability Show-1.11.2-4.1.0.jar) 
	UCHI	earthworks{1.1.1} [Earthworks] (Earthworks-1.11.2-1.1.1.jar) 
	UCHI	ea{v2.5.0a-mc1.10.2} [Ebon Arts] (EbonArts-v2.5.0a-mc1.11.0.jar) 
	UCHI	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UCHI	endores{1.0-a.013} [End Ores] (End Ores-1.0-a.013.jar) 
	UCHI	endercrop{1.11-1.3.4} [Ender Crop] (endercrop-1.11-1.3.4.jar) 
	UCHI	shetiphiancore{3.4.1} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.1.jar) 
	UCHI	endertanks{1.5.1} [EnderTanks] (endertanks-1.11.0-1.5.1.jar) 
	UCHI	enderthing{0.7.3} [Enderthing] (enderthing-1.11.0-0.7.3.jar) 
	UCHI	valkyrielib{1.11.2-0.11.0b} [Valkyrie Lib] (valkyrielib-1.11.2-0.11.0c.jar) 
	UCHI	environmentaltech{1.11.2-0.11.0d} [Environmental Tech] (environmentaltech-1.11.2-0.11.0d.jar) 
	UCHI	excore{2.0.0-alpha8-1.11.2} [EXCore] (EXCore-2.0.0-alpha8-1.11.2.jar) 
	UCHI	shadowmc{3.7.1} [ShadowMC] (ShadowMC-1.11-3.7.4.jar) 
	UCHI	extrarails{1.2.1} [Extra Rails] (ExtraRails-1.11-1.2.1.jar) 
	UCHI	zerocore{1.11.2-0.1.0.4} [Zero CORE] (zerocore-1.11.2-0.1.0.4.jar) 
	UCHI	bigreactors{1.11.2-0.4.5.27} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.27.jar) 
	UCHI	findercompass{1.11.2} [Finder Compass] (FinderCompass-1.11.2.jar) 
	UCHI	floricraft{2.0.1} [Floricraft] (Floricraft-1.11.2-2.0.1.jar) 
	UCHI	reborncore{2.13.4.37} [RebornCore] (RebornCore-1.11.2-2.13.4.37-universal.jar) 
	UCHI	reborncore-mcmultipart{2.13.4.37} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.13.4.37-universal.jar) 
	UCHI	fluxedredstone{@MODVERSION@} [FluxedRedstone] (FluxedRedstone-2.6.0.54.jar) 
	UCHI	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	UCHI	fei{1.1.0-alpha2-1.11.2} [Forever Enough Items] (Forever-Enough-Items-1.1.0-alpha2-1.11.2.jar) 
	UCHI	funnels{1.2.1} [Funnels] (Funnels-1.11-1.2.1.jar) 
	UCHI	gendustry{1.6.5.4} [GenDustry] (gendustry-1.6.5.4-mc1.11.2.jar) 
	UCHI	pressure{1.3.1.4} [Pressure Pipes] (pressure-1.3.1.4-mc1.11.2.jar) 
	UCHI	advgenerators{0.9.20.4} [Advanced Generators] (generators-0.9.20.4-mc1.11.2.jar) 
	UCHI	fishing{1.4.9} [Fishing Net Mod] (GiacomosFishingNet-1.11.2-1.4.9.jar) 
	UCHI	giacomosfoundry{1.3.11} [Giacomo's Foundry] (GiacomosFoundry-1.11.2-1.3.11.jar) 
	UCHI	giacomostravelogue{1.0.4} [Giacomo’s Travelogue] (GiacomosTravelogue-1.11.2-1.0.4.jar) 
	UCHI	glasscraftmod{2.0} [Glasscraft] (Glasscraftmod v2.0 - MC1.11 Forge.jar) 
	UCHI	guidebook{1.7.0} [Guide Book] (guidebook-1.7.0.jar) 
	UCHI	waila{1.8.10} [Waila] (Hwyla-1.8.10-B23_1.11.jar) 
	UCHI	integrateddynamics{0.6.9} [Integrated Dynamics] (IntegratedDynamics-1.11.2-0.6.9.jar) 
	UCHI	integratedtunnels{1.1.0} [Integrated Tunnels] (IntegratedTunnels-1.11.2-1.1.0.jar) 
	UCHI	ionitems{1.1.1} [Ion Items] (IonItems-1.1.1-1.11.jar) 
	UCHI	ironchest{1.11-7.0.17.799} [Iron Chest] (ironchest-1.11-7.0.17.799.jar) 
	UCHI	journeymap{1.11.2-5.4.4} [JourneyMap] (journeymap-1.11.2-5.4.4.jar) 
	UCHI	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UCHI	jet{2.1.41} [JustEnoughTooltips] (JustEnoughTooltips-1.11-2.1.41.jar) 
	UCHI	keepinginventory{2.2} [Keeping Inventory] (KeepingInventory-1.11.2-2.2.jar) 
	UCHI	lightningcraft{2.8.1} [LightningCraft] (lightningcraft-2.8.1-[1.11.2].jar) 
	UCHI	mcflux{2.4.5} [Minecraft-Flux] (mcflux-2.4.5.jar) 
	UCHI	tesla{1.3.0.51} [TESLA] (Tesla-1.11-1.3.0.51.jar) 
	UCHI	teslacorelib{0.2.0} [Tesla Core Lib] (tesla-core-lib-1.11.2-0.2.0.jar) 
	UCHI	mekfarm{0.0.1} [MekFarm] (mekfarm-1.11.2-0.2.0-HF.jar) 
	UCHI	mineclock{1.0} [MineClock] (mineclock-1.0.1.jar) 
	UCHE	modsquad{1.0} [Tesla Essentials] (modsquad-1.11-1.3.1.jar) 
	UCHI	modularrouters{1.11.2-2.1.0} [Modular Routers] (modular-routers-1.11.2-2.1.0.jar) 
	UCHI	morefurnaces{1.9.4} [More Furnaces] (MoreFurnaces-1.11-1.9.4.jar) 
	UCHI	morematerials{1.10.2-1.9.20160723.0} [More Materials] (morematerials-1.11-1.9.20160723.0.jar) 
	UCHI	multibeds{1.3.1} [Multi-Beds] (multibeds-1.11.0-1.3.1.jar) 
	UCHI	terraqueous{1.3.4} [Terraqueous] (terraqueous-1.11.0-1.3.4.jar) 
	UCHI	multistorage{1.3.2} [Multi-Storage] (multistorage-1.11.0-1.3.2.jar) 
	UCHI	mysticalagriculture{1.4.1} [Mystical Agriculture] (mysticalagriculture[1.11.2]-1.4.1.jar) 
	UCHI	samsocean{1.0.1} [Ocean Floor Classic] (OceanFloor-1.11-1.0.1.jar) 
	UCHI	packetfilter{1.3.4} [Packet Filter] (packetfilter-1.3.4.jar) 
	UCHI	harvestcraft{1.11.2d} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2d.jar) 
	UCHI	jp.crafterkina.pipes{1.1.0.12} [Pipes] (Pipes-1.11-1.1.0.12.jar) 
	UCHI	railsplus{1.0.0} [Rails Plus] (railsplus-1.0.1.jar) 
	UCHI	randomthings{3.7.9} [Random Things] (RandomThings-MC1.11.2-3.7.9.jar) 
	UCHI	rangedpumps{0.4} [Ranged Pumps] (rangedpumps-0.4.jar) 
	UCHI	redstonefluxarsenal{1.1} [Redstone Flux Arsenal] (RedstoneFluxArsenal-[1.11]-1.1.jar) 
	UCHI	refinedstorage{1.4.1} [Refined Storage] (refinedstorage-1.4.1.jar) 
	UCHI	yukarilib{1.0.2.1} [YukariLib] (YukariLib-1.0.2.1-1.11.jar) 
	UCHI	reinforcedtools{2.0.1} [ReinforcedTools] (ReinforcedTools-2.0.1-1.11.jar) 
	UCHI	rflux{0.1.0} [RF Lux] (rflux-0.1.0.jar) 
	UCHI	rftools{5.84} [RFTools] (rftools-1.1x-5.84.jar) 
	UCHI	rftoolscontrol{1.6.6} [RFTools Control] (rftoolsctrl-1.1x-1.6.6.jar) 
	UCHI	rftoolsdim{4.54} [RFTools Dimensions] (rftoolsdim-1.1x-4.54.jar) 
	UCHI	roguelike{1.6.2} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.2.jar) 
	UCHI	roots{0.009} [Roots 2] (roots-2-0.009.jar) 
	UCHI	ruins{16.4} [Ruins Mod] (Ruins-1.11.2.jar) 
	UCHI	silentlib{1.2.0} [Silent Lib] (SilentLib-1.11-1.2.0-30.jar) 
	UCHI	silentgems{2.2.9} [Silent's Gems] (SilentsGems-1.11-2.2.9-114.jar) 
	UCHI	sgextraparts{1.2.4} [Silent's Gems: Extra Parts] (SGExtraParts-1.11-1.2.4-12.jar) 
	UCHI	simplevoidworld{1.0.0.3} [SimpleVoidWorld] (Simple-Void-World-1.11-1.0.0.3-universal.jar) 
	UCHI	simplegenerators{1.11.2-0.11.0a} [Simple Generators] (simplegenerators-1.11.2-0.11.0a.jar) 
	UCHI	simplegrinder{3.060.R1112} [Simple Grinder] (SimpleGrinder-3.095.R1112.jar) 
	UCHI	lteleporters{1.11.2-2.0.2} [Simple Teleporters] (SimpleTeleporters-1.11.2-2.0.2.jar) 
	UCHI	simplyconveyors{2.1.0} [Simply Conveyors] (SimplyConveyors-2.1.2.jar) 
	UCHI	slabcraftmod{7.01} [Slabcraft] (Slabcraftmod v7.01 - MC1.11 Forge.jar) 
	UCHI	solarfluxreborn{2.12r} [Solar Flux Reborn] (SolarFluxReborn_1.11.2-2.12r.jar) 
	UCHI	solarvillage{1.2.0.26} [Solar Village] (SolarVillage-1.11-1.2.0.26.jar) 
	UCHI	sophisticatedwolves{3.6.4} [Sophisticated Wolves] (SophisticatedWolves-3.6.4.jar) 
	UCHI	spartanshields{1.2a} [Spartan Shields] (SpartanShields-1.11-1.2a.jar) 
	UCHI	staircraftmod{7.0} [Staircraft] (Staircraftmod v7.0 - MC1.11 Forge.jar) 
	UCHI	stonehenge{1.10.2-0.1} [Stonehenge] (stonehenge-1.11.2-0.1.jar) 
	UCHI	sugiforest{1.3.1} [SugiForest] (SugiForest_1.11-v1.3.1.jar) 
	UCHI	superminer_core{2.1.26.266} [SuperMiner] (SuperMiner-[1.11.2]-2.1.26.266.jar) 
	UCHI	superminer_captivator{[1.11.2]-2.1.26.266} [SuperMiner Captivator] (SuperMiner-[1.11.2]-2.1.26.266.jar) 
	UCHI	superminer_cropinator{[1.11.2]-2.1.26.266} [SuperMiner Copinator] (SuperMiner-[1.11.2]-2.1.26.266.jar) 
	UCHI	superminer_excavator{[1.11.2]-2.1.26.266} [SuperMiner Excavator] (SuperMiner-[1.11.2]-2.1.26.266.jar) 
	UCHI	superminer_illuminator{[1.11.2]-2.1.26.266} [SuperMiner Illuminator] (SuperMiner-[1.11.2]-2.1.26.266.jar) 
	UCHI	superminer_lumbinator{[1.11.2]-2.1.26.266} [SuperMiner Lumbinator] (SuperMiner-[1.11.2]-2.1.26.266.jar) 
	UCHI	superminer_shaftanator{[1.11.2]-2.1.26.266} [SuperMiner Shaftanator] (SuperMiner-[1.11.2]-2.1.26.266.jar) 
	UCHI	superminer_substitutor{[1.11.2]-2.1.26.266} [SuperMiner Substitutor] (SuperMiner-[1.11.2]-2.1.26.266.jar) 
	UCHI	superminer_veinator{[1.11.2]-2.1.26.266} [SuperMiner Veinator] (SuperMiner-[1.11.2]-2.1.26.266.jar) 
	UCHI	switchbow{1.1} [Switch-Bow] (switchbow-1.1.jar) 
	UCHI	techreborn{2.1.6.76} [TechReborn] (TechReborn-1.11.2-2.1.6.76-universal.jar) 
	UCHI	teslafied{1.0.0} [Teslafied] (teslafied-1.11-1.1.0.jar) 
	UCHI	beneath{1.2.0} [The Beneath] (The Beneath-1.11.2-1.2.0.jar) 
	UCHI	thedragonlib{1.11.2-2.2.3} [TheDragonLib] (thedragonlib-1.11.2-2.2.3.jar) 
	UCHI	thermalsolars{1.11.2 Beta V1.1} [Thermal Solars] (thermalsolars-1.11.2-1.1.jar) 
	UCHI	torchmaster{1.0} [TorchMaster] (torchmaster_1.11-1.1.0.11.jar) 
	UCHI	toroquest{1.11.2-3.2} [ToroQuest] (toroquest-1.11.2-3.2.jar) 
	UCHI	usefulrecipes{1.11-3.0.1} [UsefulRecipes] (usefulrecipes-3.0.1.jar) 
	UCHI	villagermarket{1.0} [Villager Market] (villagermarket-0.2-HF.jar) 
	UCHI	waddles{0.5.1} [Waddles] (Waddles-1.11-0.5.1.jar) 
	UCHI	witherskelefix{1} [WSkele Fixer] (Wither Skeleton Fixer-1.11.2-1.0.1.jar) 
	UCHI	yeoldetanks{1.9.3} [Ye Olde Tanks] (YeOldeTanks-1.11.2-1.9.3.jar) 
	Loaded coremods (and transformers): 
FCFMLCorePlugin (FinderCompass-1.11.2.jar)
  atomicstryker.findercompass.client.coremod.FCTransformer
RebornCoreASM (RebornCore-1.11.2-2.13.4.37-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.1.jar)
  shetiphian.core.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.11.2-3.7.9.jar)
  lumien.randomthings.asm.ClassTransformer
LoadingPlugin (Quark-r1.2-82.jar)
  vazkii.quark.base.asm.ClassTransformer
BCModPlugin (zz-backpacks 1.11.2 - 3.1.6.jar)
  brad16840.common.asm.ClassTransformer
CorePlugin (FluxedRedstone-2.6.0.54.jar)
  
CXLibraryCore (cxlibrary-1.11.2-1.4.0.jar)
  cubex2.cxlibrary.CoreModTransformer
RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  pw.prok.realbench.asm.RBTransformer
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  
SFRCore (SolarFluxReborn_1.11.2-2.12r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.53' Renderer: 'GeForce GTX 980/PCIe/SSE2'
	List of loaded APIs: 
		* Baubles|API (1.4.0.1) from Baubles-1.11-1.4.2.jar
		* BetterAchievements|API (0.4.1.44) from BetterAchievements-1.11.2-0.4.1.44.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.11.2-0.4.5.27.jar
		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-13.9.jar
		* CoFHAPI (1.8.9R1.2.0B1) from thermalsolars-1.11.2-1.1.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|core (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from thermalsolars-1.11.2-1.1.jar
		* CoFHAPI|inventory (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|transport (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* commoncapabilities|api (0.0.1) from CommonCapabilities-1.11.2-1.3.1.jar
		* compatlayer (0.1.7) from compatlayer-1.11.2-0.1.7.jar
		* convinientadditions|API (1.0) from ConvenientAdditions-1.1-build28.jar
		* CraftingTableIV-API (1.1.0) from CraftingTableIV-1.4.110.jar
		* ElecCoreAPI (1.0) from ElecCore-1.11-1.7.402.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.11-1.7.402.jar
		* environmentaltech-api (1.11.2-0.11.0d) from environmentaltech-1.11.2-0.11.0d.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.11.2-5.3.1.44.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.11.2-5.3.1.44.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.11.2-5.3.1.44.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.11.2-5.3.1.44.jar
		* ForestryAPI|core (5.1.0) from forestry_1.11.2-5.3.1.44.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.11.2-5.3.1.44.jar
		* ForestryAPI|food (1.1.0) from forestry_1.11.2-5.3.1.44.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.11.2-5.3.1.44.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.11.2-5.3.1.44.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.11.2-5.3.1.44.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.11.2-5.3.1.44.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.11.2-5.3.1.44.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.11.2-5.3.1.44.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.11.2-5.3.1.44.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.11.2-5.3.1.44.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.11.2-5.3.1.44.jar
		* ForestryAPI|world (2.1.0) from forestry_1.11.2-5.3.1.44.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.4-mc1.11.2.jar
		* integrateddynamics|api (0.2.0) from IntegratedDynamics-1.11.2-0.6.9.jar
		* jeresources|API (0.6.2.104) from JustEnoughResources-1.11.2-0.6.2.104.jar
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* jp.crafterkina.pipes.api (1.0) from Pipes-1.11-1.1.0.12.jar
		* jp.crafterkina.pipes.api.pipe (1.0) from Pipes-1.11-1.1.0.12.jar
		* jp.crafterkina.pipes.api.render (1.0) from Pipes-1.11-1.1.0.12.jar
		* JustEnoughItemsAPI (4.11.0) from jei_1.11.2-4.2.4.226.jar
		* lightningcraftAPI (2.8.1) from lightningcraft-2.8.1-[1.11.2].jar
		* mcfluxAPI|assistant (2.4.5) from mcflux-2.4.5.jar
		* mcfluxAPI|ex (2.4.5) from mcflux-2.4.5.jar
		* mcfluxAPI|fe (2.4.5) from mcflux-2.4.5.jar
		* mcjtylib_ng (2.3.9) from mcjtylib-1.1x-2.3.9.jar
		* pressureAPI (1.3.1.4) from pressure-1.3.1.4-mc1.11.2.jar
		* reborncoreAPI (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* reborncoreAPI|Fuel (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* reborncoreAPI|Power (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* reborncoreAPI|Recipe (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* reborncoreAPI|Tile (2.13.4.37) from RebornCore-1.11.2-2.13.4.37-universal.jar
		* SilentGemsAPI (2) from SilentsGems-1.11-2.2.9-114.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* sugiforest.api (1.2.0) from SugiForest_1.11-v1.3.1.jar
		* techrebornAPI (2.1.6.76) from TechReborn-1.11.2-2.1.6.76-universal.jar
		* TerraqueousAPI (1.0) from terraqueous-1.11.0-1.3.4.jar
		* TerraqueousAPI|Cloud (1.0) from terraqueous-1.11.0-1.3.4.jar
		* TerraqueousAPI|Machines (1.0) from terraqueous-1.11.0-1.3.4.jar
		* TerraqueousAPI|Plant (1.0) from terraqueous-1.11.0-1.3.4.jar
		* valkyrielib.api (1.11.2-0.11.0b) from valkyrielib-1.11.2-0.11.0c.jar
		* WailaAPI (1.3) from Hwyla-1.8.10-B23_1.11.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.11.2-0.1.0.4.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.11.2-0.1.0.4.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.11.2-0.1.0.4.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.13.4.37
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 0
`

**Comment by joernott** [comment]
Thisw is the mcflux log:
[mcflux-2017-03-03_12.02.11.txt](https://github.com/Szewek/Minecraft-Flux/files/816578/mcflux-2017-03-03_12.02.11.txt)

**Comment by joernott** [comment]
Thanks for the fast update. I can confirm the bug being gone.
