### ISSUE TITLE
[2.6.1] for 1.11.2 -- crash when attaching entity charger to neotech machines

### ISSUE THREAD

**Issue by kreezxil** [Szewek/Minecraft-Flux#18]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore v1.7.0 mc1.11.2.jar)
  Default Options (DefaultOptions_1.11.2-8.2.2.jar)
  ColorUtilityCorePlugin (ColorUtility-universal-1.0.3.jar)
  NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  FMLPlugin (InventoryTweaks-1.62+beta.84.jar)
  RebornCoreASM (RebornCore-1.11.2-2.13.6.52-universal.jar)
  LittlePatchingLoader (LittleTiles v1.4.6 mc1.11.2.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.8.jar)
  ForgelinPlugin (Forgelin-1.4.1.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 4/12/17 6:01 PM
Description: Ticking block entity

java.lang.ClassCastException: mrriegel.limelib.datapart.DataPartRegistry cannot be cast to szewek.mcflux.fluxable.WorldChunkEnergy
	at szewek.mcflux.tileentities.TileEntityWCEAware.func_73660_a(TileEntityWCEAware.java:39)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1784)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at szewek.mcflux.tileentities.TileEntityWCEAware.func_73660_a(TileEntityWCEAware.java:39)

-- Block entity being ticked --
Details:
	Name: mcflux:echarger // szewek.mcflux.tileentities.TileEntityECharger
	Block type: ID #2207 (tile.echarger // szewek.mcflux.blocks.BlockEntityCharger)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-1,87,1), Chunk: (at 15,5,1 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #2207 (tile.echarger // szewek.mcflux.blocks.BlockEntityCharger)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1802)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Kreezxil'/0, l='MpServer', x=1.28, y=86.00, z=0.08]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 06 - voidworld, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,88,0), Chunk: (at 0,5,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 243923 game time, 243923 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['Kreezxil'/0, l='MpServer', x=1.28, y=86.00, z=0.08]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_112, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1392956344 bytes (1328 MB) / 3707240448 bytes (3535 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2282 126 mods loaded, 126 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282.jar) 
	UCHIJA	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282.jar) 
	UCHIJA	ColorUtility{1.0.3} [ColorUtility] (minecraft.jar) 
	UCHIJA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJA	littletilescore{1.0.0} [LittleTilesCore] (minecraft.jar) 
	UCHIJA	backpacks16840{3.1.8} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.8.jar) 
	UCHIJA	actuallyadditions{1.11.2-r106} [Actually Additions] (ActuallyAdditions-1.11.2-r106.jar) 
	UCHIJA	opencomputers{1.7.0.6} [OpenComputers] (OpenComputers-MC1.11.2-1.7.0.6.jar) 
	UCHIJA	actuallycomputers{2.0.0} [ActuallyComputers] (actuallycomputers-2.0.0.jar) 
	UCHIJA	psi{r1.1-47} [Psi] (Psi-r1.1-47.jar) 
	UCHIJA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJA	autosapling{1.11.2-1.3.5} [AutoSapling] (AutoSapling 1.11.2-1.3.5.jar) 
	UCHIJA	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCHIJA	bdlib{1.13.2.7} [BD Lib] (bdlib-1.13.2.7-mc1.11.2.jar) 
	UCHIJA	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.11.2-1.1.7.jar) 
	UCHIJA	betterachievements{0.4.3.12} [Better Achievements] (BetterAchievements-1.11.2-0.4.3.12.jar) 
	UCHIJA	hammercore{1.5.1} [Hammer Core] (HammerCore_1.11.2-1.5.1.jar) 
	UCHIJA	blackholestorage{9r} [Black Hole Storage] (Black Hole Storage 1.11.2-9r.jar) 
	UCHIJA	theoneprobe{1.4.6} [The One Probe] (theoneprobe-1.1x-1.4.6.jar) 
	UCHIJA	modularrouters{1.11.2-2.1.1} [Modular Routers] (modular-routers-1.11.2-2.1.1.jar) 
	UCHIJA	guideapi{1.11-2.1.0-51} [Guide-API] (Guide-API-1.11-2.1.0-51.jar) 
	UCHIJA	bloodmagic{1.11-2.1.9-78} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.9-78.jar) 
	UCHIJA	bookshelfapi{5.0.0} [Bookshelf] (Bookshelf-API-1.11.2-5.0.0-B96.jar) 
	UCHIJA	badwithernocookie{1.0} [Bad Wither No Cookie!] (bwncrldd-1.0.jar) 
	UCHIJA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCHIJA	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJA	cyclopscore{0.10.0} [Cyclops Core] (CyclopsCore-1.11.2-0.10.0.jar) 
	UCHIJA	colossalchests{1.5.0} [Colossal Chests] (ColossalChests-1.11.2-1.5.0.jar) 
	UCHIJA	commoncapabilities{1.3.1} [CommonCapabilities] (CommonCapabilities-1.11.2-1.3.1.jar) 
	UCHIJA	one_point_twelve_concrete{v 1.0} [1.12 Concrete] (concreteMod-v1.0.jar) 
	UCHIJA	controlling{2.0.4} [Controlling] (Controlling-2.0.4.jar) 
	UCHIJA	cookingforblockheads{5.3.20} [Cooking for Blockheads] (CookingForBlockheads_1.11.2-5.3.20.jar) 
	UCHIJA	creativecore{1.5.0} [CreativeCore] (CreativeCore v1.7.0 mc1.11.2.jar) 
	UCHIJA	forestry{5.3.3.91} [Forestry] (forestry_1.11.2-5.3.3.91.jar) 
	UCHIJA	eleccore{1.7.415} [ElecCore] (ElecCore-1.11-1.7.415.jar) 
	UCHIJA	deepresonance{1.4.6} [DeepResonance] (deepresonance-1.1x-1.4.6.jar) 
	UCHIJA	defaultoptions{8.2.2} [Default Options] (DefaultOptions_1.11.2-8.2.2.jar) 
	UCHIJA	durabilityshow{4.1.0} [Durability Show] (Durability Show-1.11.2-4.1.0.jar) 
	UCHIJA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UCHIJA	enderrift{2.1.4} [Ender-Rift] (EnderRift-1.11.2-2.1.4.jar) 
	UCHIJA	shetiphiancore{3.4.4} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.4.jar) 
	UCHIJA	endertanks{1.5.4} [EnderTanks] (endertanks-1.11.0-1.5.4.jar) 
	UCHIJA	enderthing{0.7.3} [Enderthing] (enderthing-1.11.0-0.7.3.jar) 
	UCHIJA	valkyrielib{1.11.2-0.11.0b} [Valkyrie Lib] (valkyrielib-1.11.2-0.11.0c.jar) 
	UCHIJA	environmentaltech{1.11.2-0.11.0d} [Environmental Tech] (environmentaltech-1.11.2-0.11.0d.jar) 
	UCHIJA	etlunar{1.11.2-0.11.0c} [ET Lunar] (etlunar-1.11.2-0.11.0c.jar) 
	UCHIJA	shadowmc{3.7.1} [ShadowMC] (ShadowMC-1.11.2-3.7.5.jar) 
	UCHIJA	extrarails{1.2.1} [Extra Rails] (ExtraRails-1.11-1.2.1.jar) 
	UCHIJA	fasterladderclimbing{0.1-118} [Faster Ladder Climbing] (FasterLadderClimbing-1.11-0.1-118.jar) 
	UCHIJA	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJA	fl{1.0.2} [FL] (fl-1.0.2.jar) 
	UCHIJA	fluidconverters{2.2.1} [FluidConverters] (FluidConverters-1.11.2-2.2.1.jar) 
	UCHIJA	forgelin{1.4.1} [Forgelin] (Forgelin-1.4.1.jar) 
	UCHIJA	limelib{1.5.2} [LimeLib] (limelib-1.11.2-1.5.2.jar) 
	UCHIJA	furnus{1.92} [Furnus] (furnus-1.11.2-1.92.jar) 
	UCHIJA	gendustry{1.6.5.7} [GenDustry] (gendustry-1.6.5.7-mc1.11.2.jar) 
	UCHIJA	pressure{1.3.1.5} [Pressure Pipes] (pressure-1.3.1.5-mc1.11.2.jar) 
	UCHIJA	advgenerators{0.9.20.5} [Advanced Generators] (generators-0.9.20.5-mc1.11.2.jar) 
	UCHIJA	giacomos_bookshelf{1.1} [Giacomo's Bookshelves Mod] (GiacomosBookshelf-1.11.2-1.1.jar) 
	UCHIJA	giacomosfoundry{1.3.12} [Giacomo's Foundry] (GiacomosFoundry-1.11.2-1.3.12.jar) 
	UCHIJA	gwgmcgenmod{1.4} [gmCGENmod] (gmcgenmod-mc1.11x-v1.4.jar) 
	UCHIJA	hopperducts{1.4.9} [Hopper Ducts] (hopperducts-mc1.11.2-1.4.9.jar) 
	UCHIJA	integrateddynamics{0.6.11} [Integrated Dynamics] (IntegratedDynamics-1.11.2-0.6.11.jar) 
	UCHIJA	integratedtunnels{1.1.1} [Integrated Tunnels] (IntegratedTunnels-1.11.2-1.1.1.jar) 
	UCHIJA	inventorytweaks{1.62+beta.84.b3ecfb1} [Inventory Tweaks] (InventoryTweaks-1.62+beta.84.jar) 
	UCHIJA	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	UCHIJA	jei{4.3.1.260} [Just Enough Items] (jei_1.11.2-4.3.1.260.jar) 
	UCHIJA	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.11.2.jar) 
	UCHIJA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJA	jrftl{1.1} [jrftl] (JRFTL-1.1.jar) 
	UCHIJA	littletiles{1.3.0} [LittleTiles] (LittleTiles v1.4.6 mc1.11.2.jar) 
	UCHIJA	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	UCHIJA	mcflux{2.6.1} [Minecraft-Flux] (mcflux-2.6.1.jar) 
	UCHIJA	meta{1.2.1} [M.E.T.A.] (meta-1.2.1.jar) 
	UCHIJA	minecolonies{1.11-0.6.3360} [MineColonies] (minecolonies-universal-1.11-0.6.3360.jar) 
	UCHIJA	missing_pieces{4.1.2} [Missing Pieces] (missing_pieces-1.11.2-4.1.2.jar) 
	UCHIJA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.11.2.jar) 
	UCHIJA	mxtune{0.4.0-dev.23} [mxTune] (mxtune-1.11.2-0.4.0-dev.23.jar) 
	UCHIJA	neat{1.4-13} [Neat] (Neat 1.4-13.jar) 
	UCHIJA	neotech{5.0.0} [NeoTech] (Neotech-1.11.2-5.0.0.jar) 
	UCHIJA	nmsot{1.2.0-mc1.11.2} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.0-mc1.11.2.jar) 
	UCHIJA	recipehandler{0.8} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.8(1.11).jar) 
	UCHIJA	notenoughwands{1.5.4} [Not Enough Wands] (notenoughwands-1.1x-1.5.4.jar) 
	UCHIJA	omegacraft{1.0.0} [Omega Craft] (Omega Craft 1.0.8 -1.11.2.jar) 
	UCHIJA	omlib{1.11.2-3.0.0-61} [OMLib] (omlib-1.11.2-3.0.0-61.jar) 
	UCHIJA	ompd{3.0.0-21} [Open Modular Passive Defense] (ompd-1.10.2-3.0.0-21.jar) 
	UCHIJA	opframe{0.1} [OnlinePictureFrame] (OnlinePicFrame v1.3.4 mc1.11.2.zip) 
	UCHIJA	openmodularturrets{1.10.2-3.0.0-102} [Open Modular Turrets] (openmodularturrets-1.10.2-3.0.0-102.jar) 
	UCHIJA	oreexcavation{1.3.85} [OreExcavation] (OreExcavation-1.3.85.jar) 
	UCHIJA	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2g.jar) 
	UCHIJA	platforms{1.3.4} [Platforms] (platforms-1.11.0-1.3.4.jar) 
	UCHIJA	pulver{@VERSION@} [Pulver] (Pulver-1.11.x-1.0.0.2.jar) 
	UCHIJA	rangedpumps{0.4} [Ranged Pumps] (rangedpumps-0.4.jar) 
	UCHIJA	rarmor{1.11.2-r4.3} [Rarmor] (Rarmor-1.11.2-r4.3.jar) 
	UCHIJA	realfilingcabinet{1.2.49} [Real Filing Cabinet] (realfilingcabinet-1.11.2-1.2.49.jar) 
	UCHIJA	reborncore{2.13.6.52} [RebornCore] (RebornCore-1.11.2-2.13.6.52-universal.jar) 
	UCHIJA	reborncore-mcmultipart{2.13.6.52} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.13.6.52-universal.jar) 
	UCHIJA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.11.2-1.7.4.jar) 
	UCHIJA	refinedstorage{1.4.2} [Refined Storage] (refinedstorage-1.4.2.jar) 
	UCHIJA	xreliquary{1.11.2-1.3.3.653} [Reliquary] (Reliquary-1.11.2-1.3.3.653.jar) 
	UCHIJA	rflux{0.1.0} [RF Lux] (rflux-0.1.0.jar) 
	UCHIJA	rftools{5.92} [RFTools] (rftools-1.1x-5.92.jar) 
	UCHIJA	rftoolscontrol{1.6.6} [RFTools Control] (rftoolsctrl-1.1x-1.6.6.jar) 
	UCHIJA	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
	UCHIJA	ropebridge{2.0.5} [Rope Bridge] (ropebridge-1.11.2-2.0.5.jar) 
	UCHIJA	similsaxtranstructors{1.11.2-20} [Similsax Transtructors] (SimilsaxTranstructors-1.11.2-20.jar) 
	UCHIJA	skyresources{1.6.3} [Sky Resources] (skyresources-1.6.3.jar) 
	UCHIJA	spikemod{1.11.2-1.2.1} [Spike Mod] (spikemod-1.11.2-1.2.1.jar) 
	UCHIJA	stellarapi{0.6.4.1.3} [Stellar API] (Stellar API-0.6.4.1.3.jar) 
	UCHIJA	stellarsky{0.6.5.1.4} [Stellar Sky] (Stellar Sky-0.6.5.1.4.jar) 
	UCHIJA	storageboats{1.6} [Storage Boats Mod] (StorageBoats-1.9.jar) 
	UCHIJA	storagedrawers{1.11.2-4.2.2} [Storage Drawers] (StorageDrawers-1.11.2-4.2.2.jar) 
	UCHIJA	techreborn{2.1.11.103} [TechReborn] (TechReborn-1.11.2-2.1.11.103-universal.jar) 
	UCHIJA	thermalsolars{1.11.2 Beta V1.4} [Thermal Solars] (thermalsolars-1.11.2-1.4.jar) 
	UCHIJA	topaddons{1.11.2-0.9.2} [TOP Addons] (topaddons-1.11.2-0.9.2.jar) 
	UCHIJA	torchmaster{1.0} [TorchMaster] (torchmaster_1.11.2-1.2.1.24.jar) 
	UCHIJA	ts2k16{1.1.4} [Twerk-Sim 2K16] (TS2K16-1.1.4.jar) 
	UCHIJA	cavecraft{TSON Craft 3 - 1.9.4} [TSON Craft] (TSON Craft 4.0.6 - 1.11.2.jar) 
	UCHIJA	underphangables{1.0.4} [Underp Hangables] (underphangables-1.11.2-1.0.4.jar) 
	UCHIJA	usefulnullifiers{1.3.4} [Useful Nullifiers] (usefulnullifiers-1.3.4.jar) 
	UCHIJA	vending{1.4.3} [Vending] (vending-1.11.2-1.4.3.jar) 
	UCHIJA	voidislandcontrol{1.1.3} [Void Island Control] (voidislandcontrol-1.1.3.jar) 
	UCHIJA	weirdinggadget{1.0} [The Weirding Gadget] (weirdinggadget-1.11.2-0.1.7-universal.jar) 
	UCHIJA	woot{1.11.2-0.1.1} [Woot] (woot-1.11.2-0.1.1.jar) 
	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore v1.7.0 mc1.11.2.jar)
  
Default Options (DefaultOptions_1.11.2-8.2.2.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
ColorUtilityCorePlugin (ColorUtility-universal-1.0.3.jar)
  com.Axeryok.ColorUtility.ColorUtilityTransformer
NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
FMLPlugin (InventoryTweaks-1.62+beta.84.jar)
  invtweaks.forge.asm.ContainerTransformer
RebornCoreASM (RebornCore-1.11.2-2.13.6.52-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
LittlePatchingLoader (LittleTiles v1.4.6 mc1.11.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
BCModPlugin (zz-backpacks 1.11.2 - 3.1.8.jar)
  brad16840.common.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.4.1.jar)
  
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.66' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	List of loaded APIs: 
		* actuallyadditionsapi (33) from ActuallyAdditions-1.11.2-r106.jar
		* Baubles|API (1.4.0.2) from Baubles-1.11-1.4.3.jar
		* BetterAchievements|API (0.4.3.12) from BetterAchievements-1.11.2-0.4.3.12.jar
		* bloodmagic|API (1.11-2.1.9-78) from BloodMagic-1.11-2.1.9-78.jar
		* CoFHAPI (1.8.9R1.2.0B1) from omlib-1.11.2-3.0.0-61.jar
		* cofhapi (1.5.0) from limelib-1.11.2-1.5.2.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from omlib-1.11.2-3.0.0-61.jar
		* cofhapi|energy (1.5.0) from limelib-1.11.2-1.5.2.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.11.jar
		* commoncapabilities|api (0.0.1) from CommonCapabilities-1.11.2-1.3.1.jar
		* compatlayer (0.2.5) from compatlayer-1.11.2-0.2.5.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.1x-1.4.6.jar
		* ElecCoreAPI (1.0) from ElecCore-1.11-1.7.415.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.11-1.7.415.jar
		* environmentaltech-api (1.11.2-0.11.0d) from environmentaltech-1.11.2-0.11.0d.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|core (5.1.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|farming (2.2.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|food (1.1.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|world (2.1.0) from forestry_1.11.2-5.3.3.91.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.7-mc1.11.2.jar
		* GraphApi (1.3.0) from EnderRift-1.11.2-2.1.4.jar
		* Guide-API|API (1.11-2.1.0-51) from Guide-API-1.11-2.1.0-51.jar
		* integrateddynamics|api (0.2.0) from IntegratedDynamics-1.11.2-0.6.11.jar
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* JustEnoughItemsAPI (4.12.0) from jei_1.11.2-4.3.1.260.jar
		* mcfluxAPI|assistant (2.6.1) from mcflux-2.6.1.jar
		* mcfluxAPI|ex (2.6.1) from mcflux-2.6.1.jar
		* mcfluxAPI|fe (2.6.1) from mcflux-2.6.1.jar
		* mcjtylib_ng (2.3.11) from mcjtylib-1.1x-2.3.11.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.11.2.jar
		* opencomputersapi|component (7.0.0-alpha) from OpenComputers-MC1.11.2-1.7.0.6.jar
		* opencomputersapi|core (7.0.0-alpha) from OpenComputers-MC1.11.2-1.7.0.6.jar
		* opencomputersapi|driver (7.0.0-alpha) from OpenComputers-MC1.11.2-1.7.0.6.jar
		* opencomputersapi|driver|item (7.0.0-alpha) from OpenComputers-MC1.11.2-1.7.0.6.jar
		* opencomputersapi|event (7.0.0-alpha) from OpenComputers-MC1.11.2-1.7.0.6.jar
		* opencomputersapi|filesystem (7.0.0-alpha) from OpenComputers-MC1.11.2-1.7.0.6.jar
		* opencomputersapi|internal (7.0.0-alpha) from OpenComputers-MC1.11.2-1.7.0.6.jar
		* opencomputersapi|machine (7.0.0-alpha) from OpenComputers-MC1.11.2-1.7.0.6.jar
		* opencomputersapi|manual (7.0.0-alpha) from OpenComputers-MC1.11.2-1.7.0.6.jar
		* opencomputersapi|network (7.0.0-alpha) from OpenComputers-MC1.11.2-1.7.0.6.jar
		* opencomputersapi|prefab (7.0.0-alpha) from OpenComputers-MC1.11.2-1.7.0.6.jar
		* pressureAPI (1.3.1.5) from pressure-1.3.1.5-mc1.11.2.jar
		* PsiAPI (4) from Psi-r1.1-47.jar
		* rarmorapi (1) from Rarmor-1.11.2-r4.3.jar
		* reborncoreAPI (2.13.6.52) from RebornCore-1.11.2-2.13.6.52-universal.jar
		* reborncoreAPI|Fuel (2.13.6.52) from RebornCore-1.11.2-2.13.6.52-universal.jar
		* reborncoreAPI|Power (2.13.6.52) from RebornCore-1.11.2-2.13.6.52-universal.jar
		* reborncoreAPI|Recipe (2.13.6.52) from RebornCore-1.11.2-2.13.6.52-universal.jar
		* reborncoreAPI|Tile (2.13.6.52) from RebornCore-1.11.2-2.13.6.52-universal.jar
		* stellarapi|api (0.6.4.1.3) from Stellar API-0.6.4.1.3.jar
		* stellarsky|API (2.5) from Stellar Sky-0.6.5.1.4.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-1.4.2.jar
		* StorageDrawersAPI|config (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.2.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-1.4.2.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from refinedstorage-1.4.2.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-1.4.2.jar
		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.2.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-1.4.2.jar
		* StorageDrawersAPI|storage-attribute (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.2.jar
		* techrebornAPI (2.1.11.103) from TechReborn-1.11.2-2.1.11.103-universal.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.1x-1.4.6.jar
		* valkyrielib.api (1.11.2-0.11.0b) from valkyrielib-1.11.2-0.11.0c.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.13.6.52
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 0
	Launched Version: forge-13.20.0.2282
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 378.66, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor 
```

**Comment by kreezxil** [comment]
Also crashed the server:

Issue:  2.6.1 crashes dedicated server Forge 1.11.2 build 2282

Notes:
     crash when attaching entity charger to neotech machine

crash report:
https://gist.github.com/b90b252efea9b343e0d75990553efb37

fml server latest:
https://gist.github.com/06308a2e9de74ee0359bb3b11b01b786

**Comment by kreezxil** [comment]
Just in case I'll cross post this to limelib as it is implicated in both crash reports.

**Comment by KidsDontPlay** [comment]
my fault
