### ISSUE TITLE
server crash seens like losing something

### ISSUE THREAD

**Issue by Anonymous6214** [Szewek/Minecraft-Flux#28]
Hi developer ,I have installed your mod and place it in the server's mod folder,but it seens like losing a core or something , error code :

[00:17:33] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod mcflux (Minecraft-Flux) requires [fl@[2.11.1,)]
[00:17:33] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.MissingModsException: Mod mcflux (Minecraft-Flux) requires [fl@[2.11.1,)]
        at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264) ~[Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[00:17:33] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Users\Administrator\Desktop\1.12.2 mod\.\crash-reports\crash-2018-11-07_00.17.33-server.txt

uhh...but it didn't show me which thing I lost so I don't know how to fix it... wish you can help me solve the problem...thanks :D

**Comment by Anonymous6214** [comment]
crash report : 


---- Minecraft Crash Report ----

WARNING: coremods are present:
  weaponlib (mw-1.11.7.7_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 11/7/18 12:17 AM
Description: Exception in server tick loop

Missing Mods:
	unknown : need [2.11.1,): have missing

net.minecraftforge.fml.common.MissingModsException: Mod mcflux (Minecraft-Flux) requires [fl@[2.11.1,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 893383432 bytes (851 MB) / 1325400064 bytes (1264 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 2 total; -Xmx8192M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version           | Source                                        | Signature                                |
	|:----- |:--------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| U     | minecraft             | 1.12.2            | minecraft.jar                                 | None                                     |
	| U     | mcp                   | 9.42              | minecraft.jar                                 | None                                     |
	| U     | FML                   | 8.0.99.99         | forge-1.12.2.jar                              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | forge                 | 14.23.5.2768      | forge-1.12.2.jar                              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | securitycraft         | v1.8.9            | [1.12.2]+SecurityCraft+v1.8.9.jar             | None                                     |
	| U     | codechickenlib        | 3.1.8.341         | CodeChickenLib-1.12.2-3.1.8.341-universal.jar | None                                     |
	| U     | jei                   | 4.9.1.187         | jei_1.12.2-4.9.1.187.jar                      | None                                     |
	| U     | journeymap            | 1.12.2-5.5.2      | journeymap-1.12.2-5.5.2-tw.jar                | None                                     |
	| U     | mantle                | 1.12-1.3.3.39     | Mantle-1.12-1.3.3.39.jar                      | None                                     |
	| U     | mcflux                | 3.11.2            | mcflux-3.11.2.jar                             | None                                     |
	| U     | mw                    | 1.11.7.7          | mw-1.11.7.7_mc1.12.2.jar                      | None                                     |
	| U     | nei                   | 2.4.1             | NotEnoughItems-1.12.2-2.4.1.233-universal.jar | None                                     |
	| U     | openglider            | @VERSION@         | OpenGlider-1.12.1-1.1.0.jar                   | None                                     |
	| U     | flammpfeil.slashblade | mc1.12-r15        | SlashBlade-mc1.12-r15.jar                     | None                                     |
	| U     | tconstruct            | 1.12.2-2.11.0.106 | TConstruct-1.12.2-2.11.0.106.jar              | None                                     |

	Loaded coremods (and transformers): 
weaponlib (mw-1.11.7.7_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by szeweq** [comment]
It's written that you are missing Flux Library (fl). You can download it from [here](https://minecraft.curseforge.com/projects/fl/files).
